[camera]
position = [1.85, 1.85, -4.0]
yaw = 90.0
pitch = 0.0
fov = 60.0
focus_distance = 0.1
defocus_angle = 0.0

[world]
# Light source on ceiling
[[geometry]]
type = "quad"
origin = [1.3, 3.67, 1.3]
u = [1.1, 0.0, 0.0]
v = [0.0, 0.0, 1.1]
material = "emissive"
color = [1.0, 1.0, 1.0, 1.0]
intensity = 15.0

# Right wall (green)
[[geometry]]
type = "quad"
origin = [3.7, 0.0, 0.0]
u = [0.0, 0.0, 3.7]
v = [0.0, 3.7, 0.0]
material = "lambertian"
texture = "solid"
color = [0.12, 0.45, 0.15, 1.0]

# Left wall (red)
[[geometry]]
type = "quad"
origin = [0.0, 0.0, 0.0]
u = [0.0, 3.7, 0.0]
v = [0.0, 0.0, 3.7]
material = "lambertian"
texture = "solid"
color = [0.65, 0.05, 0.05, 1.0]

# Floor (white) - Fixed to point upward
[[geometry]]
type = "quad"
origin = [0.0, 0.0, 0.0]
u = [0.0, 0.0, 3.7]
v = [3.7, 0.0, 0.0]
material = "lambertian"
texture = "solid"
color = [0.73, 0.73, 0.73, 1.0]

# Ceiling (white) - Fixed to point downward
[[geometry]]
type = "quad"
origin = [3.7, 3.7, 3.7]
u = [-3.7, 0.0, 0.0]
v = [0.0, 0.0, -3.7]
material = "lambertian"
texture = "solid"
color = [0.73, 0.73, 0.73, 1.0]

# Back wall (white)
[[geometry]]
type = "quad"
origin = [0.0, 0.0, 3.7]
u = [0.0, 3.7, 0.0]
v = [3.7, 0.0, 0.0]
material = "lambertian"
texture = "solid"
color = [0.73, 0.73, 0.73, 1.0]

# Tall box (back right) - 165x330x165 units, rotate_y 18°, translate (265,0,295)
# Scaled to 1.1x2.2x1.1, positioned at (1.76, 0, 1.96)
[[geometry]]
type = "box"
origin = [1.76, 0.0, 1.96]
u = [1.046, 0.0, -0.340]        # 1.1 * (cos(-18°), 0, sin(-18°))
v = [0.0, 2.2, 0.0]             # height vector
w = [0.340, 0.0, 1.046]         # 1.1 * (-sin(-18°), 0, cos(-18°))
material = "lambertian"
texture = "solid"
color = [0.73, 0.73, 0.73, 1.0]

# Short box (front left) - 165×165×165 units, rotate_y 18°, translate (130,0,65)
# Scaled to 1.1×1.1×1.1, positioned at (0.87, 0, 0.43)
[[geometry]]
type = "box"
origin = [0.87, 0.0, 0.43]
u = [1.046, 0.0, 0.340]         # 1.1 * ( cos(18°), 0, sin(18°) )
v = [0.0, 1.1, 0.0]             # height vector
w = [-0.340, 0.0, 1.046]        # 1.1 * (-sin(18°), 0, cos(18°))
material = "lambertian"
texture = "solid"
color = [0.73, 0.73, 0.73, 1.0]
