[camera]
position = [1.85, 1.85, -4.0]
yaw = 90.0
pitch = 0.0
fov = 60.0
focus_distance = 0.1
defocus_angle = 0.0

[world]
# Light source on ceiling
[[geometry]]
type = "quad"
origin = [1.3, 3.67, 1.3]
u = [1.1, 0.0, 0.0]
v = [0.0, 0.0, 1.1]
material = "emissive"
color = [1.0, 1.0, 1.0, 1.0]
intensity = 15.0

# Right wall (green)
[[geometry]]
type = "quad"
origin = [3.7, 0.0, 0.0]
u = [0.0, 0.0, 3.7]
v = [0.0, 3.7, 0.0]
material = "lambertian"
texture = "solid"
color = [0.12, 0.45, 0.15, 1.0]

# Left wall (red)
[[geometry]]
type = "quad"
origin = [0.0, 0.0, 0.0]
u = [0.0, 3.7, 0.0]
v = [0.0, 0.0, 3.7]
material = "lambertian"
texture = "solid"
color = [0.65, 0.05, 0.05, 1.0]

# Floor (white) - Fixed to point upward
[[geometry]]
type = "quad"
origin = [0.0, 0.0, 0.0]
u = [0.0, 0.0, 3.7]
v = [3.7, 0.0, 0.0]
material = "lambertian"
texture = "solid"
color = [0.73, 0.73, 0.73, 1.0]

# Ceiling (white) - Fixed to point downward
[[geometry]]
type = "quad"
origin = [3.7, 3.7, 3.7]
u = [-3.7, 0.0, 0.0]
v = [0.0, 0.0, -3.7]
material = "lambertian"
texture = "solid"
color = [0.73, 0.73, 0.73, 1.0]

# Back wall (white)
[[geometry]]
type = "quad"
origin = [0.0, 0.0, 3.7]
u = [0.0, 3.7, 0.0]
v = [3.7, 0.0, 0.0]
material = "lambertian"
texture = "solid"
color = [0.73, 0.73, 0.73, 1.0]
